version: '3.9'
services:
  saraswati-dashboard:
    build:
      context: .
    image: amidatech/saraswati-dashboard
    container_name: saraswati-dashboard
    # Set environment variables from this file
    env_file:
      - .env
    ports:
      - "3000:80"
    networks:
      - cpc_default
networks:
  cpc_default:
    name: cp-all-in-one-community_default
