import mockTrend from './mockTrend'
import mockSearch from './mockSearch'
// trendPromise : measures/trends?legacyResults=
export const mockTrendPromise = mockTrend;
// searchPromise - legacy results : measures/searchResults
export const mockLegacySearchPromise = {};
// searchPromise - results : measures/dailyMeasureResults
export const mockSearchPromise = mockSearch;
// infoPromise : measures/info
export const mockInfoPromise = {
  composite: {
    title: 'Composite Score',
    displayLabel: 'Composite',
    hasSubMeasures: false,
  },
  aab: {
    domainOfCare: 'EOC',
    title: 'Avoidance of Antibiotic Treatment in Adults with Acute Bronchitis',
    displayLabel: 'AAB',
    description:
      'AAB assesses the percentage of episodes for members 3 months of age and older with a diagnosis of acute bronchitis/bronchiolitis that did not result in an antibiotic dispensing event.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: true,
    link: 'https://www.ncqa.org/hedis/measures/avoidance-of-antibiotic-treatment-for-acute-bronchitis-bronchiolitis/',
  },
  adde: {
    domainOfCare: 'ECDS',
    title: 'Follow-Up Care for Children Prescribed ADHD Medication',
    displayLabel: 'ADD-E',
    description:
      'ADD-E assesses follow-up care for children prescribed an ADHD medication in the Initiation and Continuation & Maintenance phases.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/follow-up-care-for-children-prescribed-adhd-medication/',
  },
  'adde-1': {
    domainOfCare: 'ECDS',
    title: 'Follow-Up Care After Initiation of Treatment',
    displayLabel: 'ADD-E: Follow-Up After Initiation',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/follow-up-care-for-children-prescribed-adhd-medication/',
  },
  'adde-2': {
    domainOfCare: 'ECDS',
    title: 'Follow-Up Care After Initiation of Treatment',
    displayLabel: 'ADD-E: Follow-Up During Continuation',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/follow-up-care-for-children-prescribed-adhd-medication/',
  },
  apme: {
    domainOfCare: 'ECDS',
    title:
      'Metabolic Monitoring for Children and Adolescents on Antipsychotics',
    displayLabel: 'APM-E',
    description:
      'APM-E assesses the percentage of children and adolescents with ongoing antipsychotic medication use who had metabolic testing during the year.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/metabolic-monitoring-for-children-and-adolescents-on-antipsychotics/',
  },
  'apme-1': {
    domainOfCare: 'ECDS',
    title:
      'Blood Glucose Monitoring for Children and Adolescents on Antipsychotics',
    displayLabel: 'APM-E: Blood Glucose Monitoring',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/metabolic-monitoring-for-children-and-adolescents-on-antipsychotics/',
  },
  'apme-2': {
    domainOfCare: 'ECDS',
    title:
      'Cholesterol Monitoring for Children and Adolescents on Antipsychotics',
    displayLabel: 'APM-E: Cholesterol Monitoring',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/metabolic-monitoring-for-children-and-adolescents-on-antipsychotics/',
  },
  'apme-3': {
    domainOfCare: 'ECDS',
    title:
      'Blood Glucose and Cholesterol Monitoring for Children and Adolescents on Antipsychotics',
    displayLabel: 'APM-E: Blood Glucose and Cholesterol Monitoring',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/metabolic-monitoring-for-children-and-adolescents-on-antipsychotics/',
  },
  asfe: {
    domainOfCare: 'ECDS',
    title: 'Unhealthy Alcohol Use Screening and Follow-Up',
    displayLabel: 'ASF-E',
    description:
      'ASF-E assesses the percentage of members 18 years and older who were screened for unhealthy alcohol use and received appropriate follow-up care if they screened positive.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/unhealthy-alcohol-use-screening-and-follow-up/',
  },
  'asfe-1': {
    domainOfCare: 'ECDS',
    title: 'Unhealthy Alcohol Use Screening',
    displayLabel: 'ASF-E: Unhealthy Alcohol Use Screening',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/unhealthy-alcohol-use-screening-and-follow-up/',
  },
  'asfe-2': {
    domainOfCare: 'ECDS',
    title:
      'Counseling or Other Follow-Up on Positive Screen for Unhealthy Alcohol Use',
    displayLabel: 'ASF-E: Follow-Up',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/unhealthy-alcohol-use-screening-and-follow-up/',
  },
  aise: {
    domainOfCare: 'ECDS',
    title: 'Adult Immunization Status',
    displayLabel: 'AIS-E',
    description:
      'AIS-E assesses the percentage of members 19 years and older who are up-to-date on vaccines for influenza, TD or tetanus, TDaP, zoster and pneumococcal.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/adult-immunization-status/',
  },
  'aise-1': {
    domainOfCare: 'ECDS',
    title: 'Adult Immunization Status: Influenza',
    displayLabel: 'AIS-E: Influenza',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/adult-immunization-status/',
  },
  'aise-2': {
    domainOfCare: 'ECDS',
    title: 'Adult Immunization Status: Td/Tdap',
    displayLabel: 'AIS-E: Td/Tdap',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/adult-immunization-status/',
  },
  'aise-3': {
    domainOfCare: 'ECDS',
    title: 'Adult Immunization Status: Zoster',
    displayLabel: 'AIS-E: Zoster',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/adult-immunization-status/',
  },
  'aise-4': {
    domainOfCare: 'ECDS',
    title: 'Adult Immunization Status: Pneumococcal',
    displayLabel: 'AIS-E: Pneumococcal',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/adult-immunization-status/',
  },
  bcse: {
    domainOfCare: 'ECDS',
    title: 'Breast Cancer Screening Rate',
    displayLabel: 'BCS-E',
    description:
      'BCS-E assesses women 50-74 years of age who had at least one mammogram to screen for breast cancer in the past two years.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/breast-cancer-screening/',
  },
  ccs: {
    domainOfCare: 'EOF',
    title: 'Cervical Cancer Screening Rate',
    displayLabel: 'CCS',
    description:
      'CCS assesses women who were screened for cervical cancer with certain conditions applied to the following age brackets: 21–64 years and 30–64 years.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/cervical-cancer-screening/',
  },
  cise: {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status',
    displayLabel: 'CIS-E',
    description:
      'CIS-E assesses the percentage of children 2 years of age who had four DTaP, three IPV, 1 MMR, three HiB, three HepB, one VZV, four PCV, one HepA, two or three RV and two flu vaccines by their second birthday.',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-1': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: DTaP',
    displayLabel: 'CIS-E: DTaP',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-2': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: IPV',
    displayLabel: 'CIS-E: IPV',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-3': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: MMR',
    displayLabel: 'CIS-E: MMR',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-4': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: HiB',
    displayLabel: 'CIS-E: HiB',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-5': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: Hepatitus B',
    displayLabel: 'CIS-E: Hepatitus B',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-6': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: VZV',
    displayLabel: 'CIS-E: VZV',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-7': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: Pneumococcal Conjugate',
    displayLabel: 'CIS-E: Pneumococcal Conjugate',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-8': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: Hepatitus A',
    displayLabel: 'CIS-E: Hepatitus A',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-9': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: Rotavirus',
    displayLabel: 'CIS-E: Rotavirus',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-10': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: Influenza',
    displayLabel: 'CIS-E: Influenza',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-11': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: Combination 3',
    displayLabel: 'CIS-E: Combination 3',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-12': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: Combination 7',
    displayLabel: 'CIS-E: Combination 7',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  'cise-13': {
    domainOfCare: 'ECDS',
    title: 'Childhood Immunization Status: Combination 10',
    displayLabel: 'CIS-E: Combination 10',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/childhood-immunization-status/',
  },
  cole: {
    domainOfCare: 'ECDS',
    title: 'Colorectal Cancer Screening Rate',
    displayLabel: 'CCS',
    description:
      'COL assesses adults 50-75 who had appropriate screening for colorectal cancer with the appropriate designated tests.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/colorectal-cancer-screening/',
  },
  cou: {
    domainOfCare: 'EOC',
    title: 'Risk of Continued Opioid Use',
    displayLabel: 'COU',
    description:
      'COU assesses potentially high-risk opioid analgesic prescribing practices with members 18 years and older who have a new episode of opioid use that puts them at risk for continued opioid use.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/risk-of-continued-opioid-use/',
  },
  'cou-1': {
    domainOfCare: 'EOC',
    title: '15 or More Days of Opioid Medications in 30 Day Period',
    displayLabel: 'COU: 15 Days Opioid Medications',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/risk-of-continued-opioid-use/',
  },
  'cou-2': {
    domainOfCare: 'EOC',
    title: '31 or More Days of Opioid Medications in 62 Day Period',
    displayLabel: 'COU: 31 Days Opioid Medications',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/risk-of-continued-opioid-use/',
  },
  cwp: {
    domainOfCare: 'EOC',
    title: 'Appropriate Testing for Children with Pharyngitis',
    displayLabel: 'CWP',
    description:
      'CWP assesses the percentage of episodes for members 3 years and older with a diagnosis of pharyngitis, dispensed an antibiotic and received a group A streptococcus test for the episode.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/appropriate-testing-for-pharyngitis/',
  },
  dmse: {
    domainOfCare: 'ECDS',
    title: 'Monitor Depression Symptoms for Adolescents and Adults',
    displayLabel: 'DMS-E',
    description:
      'DMS-E assesses the percentage of members 12 years and older diagnosed with major depression or dysthymia and an outpatient encounter with a PHQ-9 score in their record at the same time as the encounter.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/utilization-of-the-phq-9-to-monitor-depression-symptoms-for-adolescents-and-adults/',
  },
  'dmse-1': {
    domainOfCare: 'ECDS',
    title: 'Assessment Period 1: January 1 - April 30',
    displayLabel: 'DMS-E: Assessment Period 1',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/utilization-of-the-phq-9-to-monitor-depression-symptoms-for-adolescents-and-adults/',
  },
  'dmse-2': {
    domainOfCare: 'ECDS',
    title: 'Assessment Period 2: May 1 - August 31',
    displayLabel: 'DMS-E: Assessment Period 2',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/utilization-of-the-phq-9-to-monitor-depression-symptoms-for-adolescents-and-adults/',
  },
  'dmse-3': {
    domainOfCare: 'ECDS',
    title: 'Assessment Period 3: September 1 - December 31',
    displayLabel: 'DMS-E: Assessment Period 3',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/utilization-of-the-phq-9-to-monitor-depression-symptoms-for-adolescents-and-adults/',
  },
  drre: {
    domainOfCare: 'ECDS',
    title: 'Depression Remission or Response for Adolescents and Adults',
    displayLabel: 'DRR-E',
    description:
      'DRR-E assesses the percentage of members 12 years and older with a diagnosis of depression and an elevated PHQ-9 score, who had evidence of response or remission within 4–8 months of the elevated score.',
    measureType: 'outcome',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/depression-remission-or-response-for-adolescents-and-adults/',
  },
  'drre-1': {
    domainOfCare: 'ECDS',
    title: 'Depression Follow-Up for Adolescents and Adults',
    displayLabel: 'DRR-E: Follow-Up',
    measureType: 'outcome',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/depression-remission-or-response-for-adolescents-and-adults/',
  },
  'drre-2': {
    domainOfCare: 'ECDS',
    title: 'Depression Remission for Adolescents and Adults',
    displayLabel: 'DRR-E: Remission',
    measureType: 'outcome',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/depression-remission-or-response-for-adolescents-and-adults/',
  },
  'drre-3': {
    domainOfCare: 'ECDS',
    title: 'Depression Response for Adolescents and Adults',
    displayLabel: 'DRR-E: Response',
    measureType: 'outcome',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/depression-remission-or-response-for-adolescents-and-adults/',
  },
  dsfe: {
    domainOfCare: 'ECDS',
    title: 'Depression Screening and Follow-Up for Adolescents and Adults',
    displayLabel: 'DSF-E',
    description:
      'DSF-E assesses the percentage of members 12 years and older who were screened for clinical depression using a standardized instrument and, if screened positive, received follow-up care.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/depression-screening-and-follow-up-for-adolescents-and-adults/',
  },
  'dsfe-1': {
    domainOfCare: 'ECDS',
    title: 'Depression Screening for Adolescents and Adults',
    displayLabel: 'DSF-E: Depression Screening',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/depression-screening-and-follow-up-for-adolescents-and-adults/',
  },
  'dsfe-2': {
    domainOfCare: 'ECDS',
    title: 'Follow-Up on Positive Depression Screen for Adolescents and Adults',
    displayLabel: 'DSF-E: Follow-Up on Positive Screen',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/depression-screening-and-follow-up-for-adolescents-and-adults/',
  },
  fum: {
    domainOfCare: 'EOC',
    title: 'Follow-Up After Emergency Department Visit for Mental Illness',
    displayLabel: 'FUM',
    description:
      'FUM assesses ED visits for adults and children 6 years and older with a diagnosis of mental illness or intentional self-harm and who received a follow-up visit for mental illness within 7 - 30 days.',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/follow-up-after-emergency-department-visit-for-mental-illness/',
  },
  'fum-1': {
    domainOfCare: 'EOC',
    title: 'Follow-Up Within 7 Days of Emergancy Department Visit',
    displayLabel: 'FUM: Follow-Up Within 7 Days',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/follow-up-after-emergency-department-visit-for-mental-illness/',
  },
  'fum-2': {
    domainOfCare: 'EOC',
    title: 'Follow-Up Within 30 Days of Emergancy Department Visit',
    displayLabel: 'FUM: Follow-Up Within 30 Days',
    measureType: 'process',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/follow-up-after-emergency-department-visit-for-mental-illness/',
  },
  imae: {
    domainOfCare: 'ECDS',
    title: 'Immunizations for Adolescents',
    displayLabel: 'IMA-E',
    description:
      'IMA-E assesses adolescents 13 years of age who had one dose of meningococcal vaccine, one Tdap vaccine and the complete human papillomavirus vaccine series by their 13th birthday.',
    measureType: 'outcome',
    weight: 3,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/immunizations-for-adolescents/',
  },
  'imae-1': {
    domainOfCare: 'ECDS',
    title: 'Meningococcal Serogroups A, C, W, Y',
    displayLabel: 'IMA-E: Meningococcal',
    measureType: 'outcome',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/immunizations-for-adolescents/',
  },
  'imae-2': {
    domainOfCare: 'ECDS',
    title: 'Tdap',
    displayLabel: 'IMA-E: Tdap',
    measureType: 'outcome',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/immunizations-for-adolescents/',
  },
  'imae-3': {
    domainOfCare: 'ECDS',
    title: 'HPV',
    displayLabel: 'IMA-E: HPV',
    measureType: 'outcome',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/immunizations-for-adolescents/',
  },
  'imae-4': {
    domainOfCare: 'ECDS',
    title: 'Combination 1: Meningococcal, Tdap',
    displayLabel: 'IMA-E: Combination 1',
    measureType: 'outcome',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/immunizations-for-adolescents/',
  },
  'imae-5': {
    domainOfCare: 'ECDS',
    title: 'Combination 2: Meningococcal, Tdap, HPV',
    displayLabel: 'IMA-E: Combination 2',
    measureType: 'outcome',
    weight: 3,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/immunizations-for-adolescents/',
  },
  pdse: {
    domainOfCare: 'ECDS',
    title: 'Postpartum Depression Screening and Follow-up',
    displayLabel: 'PDS-E',
    description:
      'PDS-E assesses the percentage of deliveries in which members were screened for clinical depression during the postpartum period, and if screened positive, received follow-up care.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/postpartum-depression-screening-and-follow-up/',
  },
  'pdse-1': {
    domainOfCare: 'ECDS',
    title: 'Postpartum Depression Screening',
    displayLabel: 'PDS-E: Depression Screening',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/postpartum-depression-screening-and-follow-up/',
  },
  'pdse-2': {
    domainOfCare: 'ECDS',
    title: 'Follow-Up on Positive Postpartum Depression Screen',
    displayLabel: 'PDS-E: Follow-Up on Positive Screen',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/postpartum-depression-screening-and-follow-up/',
  },
  pnde: {
    domainOfCare: 'ECDS',
    title: 'Prenatal Depression Screening and Follow-up',
    displayLabel: 'PND-E',
    description:
      'PND-E assesses the percentage of deliveries in which members were screened for clinical depression while pregnant and, if screened positive, received follow-up care.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/prenatal-depression-screening-and-followup/',
  },
  'pnde-1': {
    domainOfCare: 'ECDS',
    title: 'Prenatal Depression Screening',
    displayLabel: 'PND-E: Depression Screening',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/prenatal-depression-screening-and-followup/',
  },
  'pnde-2': {
    domainOfCare: 'ECDS',
    title: 'Follow-Up on Positive Prenatal Depression Screen',
    displayLabel: 'PND-E: Follow-Up on Positive Screen',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/prenatal-depression-screening-and-followup/',
  },
  prse: {
    domainOfCare: 'ECDS',
    title: 'Prenatal Immunization Status',
    displayLabel: 'PRS-E',
    description:
      'PRS-E assesses the percentage of deliveries in the measurement period in which women received influenza and tetanus, diphtheria toxoids and acellular pertussis (Tdap) vaccinations.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/prenatal-immunization-status/',
  },
  'prse-1': {
    domainOfCare: 'ECDS',
    title: 'Immunization Status: Influenza',
    displayLabel: 'PRS-E: Influenza',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/prenatal-immunization-status/',
  },
  'prse-2': {
    domainOfCare: 'ECDS',
    title: 'Immunization Status: Tdap',
    displayLabel: 'PRS-E: Tdap',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/prenatal-immunization-status/',
  },
  'prse-3': {
    domainOfCare: 'ECDS',
    title: 'Immunization Status: Influenza and Tdap',
    displayLabel: 'PRS-E: Combination',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/prenatal-immunization-status/',
  },
  psa: {
    domainOfCare: 'EOC',
    title: 'Non-Recommended PSA-Based Screening in Older Men',
    displayLabel: 'PSA',
    description:
      'PSA assesses whether men 70 years and older were screened unnecessarily for prostate cancer using prostate-specific antigen (PSA)-based screening.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/non-recommended-psa-based-screening-in-older-men/',
  },
  uop: {
    domainOfCare: 'EOC',
    title: 'Use of Opioids from Multiple Providers',
    displayLabel: 'UOP',
    description:
      'UOP assesses potentially high-risk opioid analgesic prescribing practices via the proportion of members 18 years and older, receiving prescription opioids for more than 15 days during the year from multiple providers.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: true,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/use-of-opioids-from-multiple-providers/',
  },
  'uop-1': {
    domainOfCare: 'EOC',
    title: 'Use of Opioids from Multiple Prescribers',
    displayLabel: 'UOP: Multiple Prescribers',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/use-of-opioids-from-multiple-providers/',
  },
  'uop-2': {
    domainOfCare: 'EOC',
    title: 'Use of Opioids from Multiple Pharmacies',
    displayLabel: 'UOP: Multiple Pharmacies',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/use-of-opioids-from-multiple-providers/',
  },
  'uop-3': {
    domainOfCare: 'EOC',
    title: 'Use of Opioids from Multiple Prescribers and Pharmacies',
    displayLabel: 'UOP: Multiple Prescribers and Pharmacies',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: false,
    link: 'https://www.ncqa.org/hedis/measures/use-of-opioids-from-multiple-providers/',
  },
  uri: {
    domainOfCare: 'EOC',
    title:
      'Appropriate Treatment for Children With Upper Respiratory Infection',
    displayLabel: 'URI',
    description:
      'URI assesses the percentage of episodes for members 3 months and older diagnosed with an URI that did not result in an antibiotic dispensing event.',
    measureType: 'process',
    weight: 1,
    hasSubMeasures: false,
    inverted: true,
    link: 'https://www.ncqa.org/hedis/measures/appropriate-treatment-for-upper-respiratory-infection/',
  },
};
// payorsPromise : payors
export const mockPayorsPromise = {
  payors: [
    {
      _id: '679d034921f6270031256870',
      payor: 'Organization/1',
      value: 'Organization/1',
      timestamp: '2025-01-31T17:07:21.899Z',
    },
    {
      _id: '679d034921f627003125686e',
      payor: 'Organization/3',
      value: 'Organization/3',
      timestamp: '2025-01-31T17:07:21.897Z',
    },
    {
      _id: '679d034921f627003125686f',
      payor: 'Organization/2',
      value: 'Organization/2',
      timestamp: '2025-01-31T17:07:21.898Z',
    },
  ],
};
// healthcareProvidersPromise : healthcareproviders
export const mockHealthcareProvidersPromise = {
  healthcareProviders: [
    {
      _id: '679d034921f6270031256877',
      provider: 'Norton Hill Carecenter',
      value: 'Organization?identifier=71533123',
      timestamp: '2025-01-31T17:07:21.902Z',
    },
    {
      _id: '679d034921f627003125687a',
      provider: "Anova Women's Birthing Service",
      value: 'Organization?identifier=9911',
      timestamp: '2025-01-31T17:07:21.903Z',
    },
    {
      _id: '679d034921f627003125687e',
      provider: 'Springfield Hospital',
      value: 'Organization?identifier=71533123',
      timestamp: '2025-01-31T17:07:21.902Z',
    },
    {
      _id: '679d034921f6270031256878',
      provider: 'Hollifield Clinics',
      value: 'Organization?identifier=667531',
      timestamp: '2025-01-31T17:07:21.902Z',
    },
    {
      _id: '679d034921f6270031256879',
      provider: 'Cancer Treatment & Care',
      value: 'Organization?identifier=8554',
      timestamp: '2025-01-31T17:07:21.903Z',
    },
  ],
};
// healthcareCoveragesPromise : healthcarecoverages
export const mockHealthcareCoveragesPromise = {
  healthcareCoverages: [
    {
      _id: '679d034921f627003125687b',
      coverage: 'Health Maintenance Organization Policy',
      value: 'HMO',
      timestamp: '2025-01-31T17:07:21.903Z',
    },
    {
      _id: '679d034921f627003125687c',
      coverage: 'Managed Care Policy',
      value: 'MCPOL',
      timestamp: '2025-01-31T17:07:21.903Z',
    },
    {
      _id: '679d034921f627003125687d',
      coverage: 'Preferred Provider Organization Policy',
      value: 'PPO',
      timestamp: '2025-01-31T17:07:21.903Z',
    },
  ],
};
// practitionersPromise : practitioners
export const mockPractitionersPromise = {
  practitioner: [
    {
      _id: '679d034921f6270031256871',
      practitioner: 'Doctor Anne Guish',
      value: 'Practitioner?identifier=1143',
      timestamp: '2025-01-31T17:07:21.899Z',
    },
    {
      _id: '679d034921f6270031256876',
      practitioner: 'Dr. Colette DeBarge',
      value: 'Practitioner?identifier=8123',
      timestamp: '2025-01-31T17:07:21.901Z',
    },
    {
      _id: '679d034921f6270031256872',
      practitioner: 'Nurse Karen Patches',
      value: 'Practitioner?identifier=1221',
      timestamp: '2025-01-31T17:07:21.900Z',
    },
    {
      _id: '679d034921f6270031256873',
      practitioner: 'Nurse Practitioner Sharon Arthurs',
      value: 'Practitioner?identifier=7882499',
      timestamp: '2025-01-31T17:07:21.900Z',
    },
    {
      _id: '679d034921f6270031256874',
      practitioner: 'Dr. Marc Weber, General Practitioner',
      value: 'Practitioner?identifier=1143',
      timestamp: '2025-01-31T17:07:21.900Z',
    },
    {
      _id: '679d034921f6270031256875',
      practitioner: 'Dr. Larry McDaniels',
      value: 'Practitioner?identifier=903321',
      timestamp: '2025-01-31T17:07:21.901Z',
    },
  ],
};
